### ISSUE TITLE
Missing semicolon

### ISSUE THREAD

**Issue by Embraser01** [lukejacksonn/perflink#10]
When testing, we need to add a semicolon in some cases:

[Like here](https://perf.link/#Y29uc3QgZGF0YSA9IFsuLi5BcnJheSgxMDAwMDApLmtleXMoKV0=/W3siY29kZSI6IjtbXS5jb25jYXQoZGF0YSkiLCJtZWRpYW4iOjAuNjIwMDAwMDA2MTY1MzU1NCwiZXJyb3IiOmZhbHNlfSx7ImNvZGUiOiI7Wy4uLmRhdGFdIiwiZXJyb3IiOmZhbHNlLCJtZWRpYW4iOjAuNTU5OTk5OTU2NzQ5Mzc5Nn0seyJjb2RlIjoiZGF0YS5zbGljZSgwKSIsImVycm9yIjpmYWxzZSwibWVkaWFuIjowLjcxNTAwMDAzMTA1MDI5NDZ9LHsiY29kZSI6ImRhdGEuc2xpY2UoKSIsImVycm9yIjpmYWxzZSwibWVkaWFuIjowLjU5NDk5OTk5MDQyNjAwMzl9XQ==)

The solution would be to simply add semicolon in the test script:

https://github.com/lukejacksonn/perflink/blob/6414d3f9622fec7549ec5750e956385eaffb5c62/routes/home/index.js#L45-L51

**Comment by lukejacksonn** [comment]
Nice! Fancy making a PR? If not I will get around to it asap. Good spot! 🙇

**Comment by Embraser01** [comment]
I'll make a PR in a few minutes😄 

Nice work BTW

**Comment by lukejacksonn** [comment]
Opops, I already pushed it 
https://github.com/lukejacksonn/perflink/commit/ac498e4b393247182dd353399c2c0cd5b66677b0

But I merged your PR anyway! Thanks for taking the time to address this 🙇 

Here is the [test case]|(#Y29uc3QgZGF0YSA9IFsuLi5BcnJheSgxMDAwMDApLmtleXMoKV0=/W3siY29kZSI6IltdLmNvbmNhdChkYXRhKSIsIm1lZGlhbiI6MCwiZXJyb3IiOnRydWV9LHsiY29kZSI6IlsuLi5kYXRhXSIsImVycm9yIjp0cnVlLCJtZWRpYW4iOjB9LHsiY29kZSI6ImRhdGEuc2xpY2UoMCkiLCJlcnJvciI6ZmFsc2UsIm1lZGlhbiI6MC40NDk5OTk5OTk1NDU5ODAyNH0seyJjb2RlIjoiZGF0YS5zbGljZSgpIiwiZXJyb3IiOmZhbHNlLCJtZWRpYW4iOjAuNDY5OTk5OTk5MDQwNzM3NzV9XQ==) you gave but working without the manually added semicolons
