### ISSUE TITLE
Infinite Alert

### ISSUE THREAD

**Issue by jesseokeya** [lukejacksonn/perflink#12]
whenever I input alert it keeps on alerting until the page is refreshed

**Comment by lukejacksonn** [comment]
Ahh.. yes, it will run it 100 times 😄 perhaps there should be a regex to prevent running certain snippets? Or by changing the way perf is measured; we could measure how many executions happen in a second. This approach would alleviate some other issues like firefox and safari's poor timer resolutions.

**Comment by jesseokeya** [comment]
Yh I agree with the regex approach to check on certain code snippets. ill create a pull request to fix the issue.

**Comment by lukejacksonn** [comment]
Hey @jesseokeya I have recently updated perflink and now tests don't run on keypress.. so if you enter an alert and then hit run.. you only have yourself to blame 😅 it still might be an idea to have a regex to warn people about this but hopefully this new approach limits the potential damage.

Lmk if you have any other ideas! 🙇
