### ISSUE TITLE
test cases making network requests

### ISSUE THREAD

**Issue by EricEisaman** [lukejacksonn/perflink#16]
As so many performance scenarios involve network requests, it would be nice if perflink, detected network requests and offered a few request batch sizes to run, from which a statistical performance graph would display as the result.  I think this could well address the variability involved, even if the request targets are mocked in local cache.

**Comment by lukejacksonn** [comment]
This is a good point and raises the issue more generally about any code that is async (like a setTimeout or a promise for example) that currently would appear to execute instantly. I haven't looked into how best to support this kind of thing yet but I will do and am all ears for suggestions!

**Comment by lukejacksonn** [comment]
This has been implemented in V2 (here #24). Both top level await, promises and es-module imports are now supported (import syntax only works if your browser supports worker type module which is currently only chrome).

Hope that helps, apologies it took so long to resolve. Thanks 🙇
