### ISSUE TITLE
Lengthy base64 string in link is not discussion board friendly

### ISSUE THREAD

**Issue by EricEisaman** [lukejacksonn/perflink#17]
Providing a built-in url shortener solution would increase the utility value to developers using this tool in discussion boards which frown upon posting links with large base64 strings.

**Comment by lukejacksonn** [comment]
Can people not shorten their own URLs? Do you know any good url shortening as a service APIs? I was surprised that Twitter can handle these base64 urls (it shortens them for you).

**Comment by EricEisaman** [comment]
I admit, this is a wishful and lazy-ish request.

I did find this:
[](https://glitch.com/edit/#!/frankbearzou-url-shortener?path=README.md:1:0)

I can remix it into a Node.js project with a service endpoint and submit a pull request.  It would be better if it was hosted on now.sh as those containers spin up much more quickly.  Maybe someone already has such a service on now.sh.  I will look.

**Comment by lukejacksonn** [comment]
I'm going to close this here.. if you find anything interesting let me know!
