### ISSUE TITLE
Does not support Cyrillic

### ISSUE THREAD

**Issue by snatvb** [lukejacksonn/perflink#21]
After copy-paste with comment the app will throw exception, my comments  was in cyrillic

**Comment by lukejacksonn** [comment]
This might have something to do with the `atob` conversion which I believe cannot handle none ascii characters like emojis for example. This could probably be fixed but it is of low priority for me at the moment. If you come up with a fix then I'd welcome a PR!

**Comment by lukejacksonn** [comment]
I _think_ this is fixed in #24 I wasn't url encoding the atob result before and any forward slashes were messing with the decoding. If you still remember how to reproduce then please try again and lmk! Otherwise I hope you enjoy the improvements 🙇
