### ISSUE TITLE
Stop run tests every time on every keypress

### ISSUE THREAD

**Issue by HawkeyePierce89** [lukejacksonn/perflink#22]
Please, it's terrible. Rerun tests on `onfocus` will be more friendly

**Comment by lukejacksonn** [comment]
There should probably be an option to disable the run on keypress. How about you make a PR?

**Comment by lukejacksonn** [comment]
This is fixed in V2 #24 sorry it took so long to get around to fixing it. In retrospect it was a very bad UX decision 😅 hope you like the new approach (either click run or cmd+enter hotkey).
