### ISSUE TITLE
OG meta tags

### ISSUE THREAD

**Issue by mantovanig** [lukejacksonn/perflink#29]
There are no open graph meta tags inside home page HTML

**Comment by lukejacksonn** [comment]
This is certainly something I should add 👍 I have some screenshots and things for the images although eventually I'd really like to give previews of test urls like https://bundlephobia.com does.. its so slick the way they do that. I'm guess they use a lambda service or something.

**Comment by mantovanig** [comment]
Yes! It's very slick :)
