### ISSUE TITLE
Dynamic import doesn't work in Firefox

### ISSUE THREAD

**Issue by lukejacksonn** [lukejacksonn/perflink#5]
Add a ponyfill, probably this https://github.com/lukeed/dynamic-import-ponyfill

**Comment by lukejacksonn** [comment]
So, turns out firefox isn't worth supporting anyway.. all results are 0 because:

![Screen Shot 2019-04-02 at 18 23 22](https://user-images.githubusercontent.com/1457604/55423695-5873d980-5576-11e9-8aec-d47051a091d0.png)

We tried.. and I thank you again for your efforts, but principally I'm not that into supporting browsers that don't uphold standards that help us be effective developers.

There has been a suggestion that for safari and firefox we run a seconds worth of iterations and then count how many occurred and report back that metric instead. Which would work I guess but I will have to experiment.

**Comment by Draluy** [comment]
Hi, I'm having the error "SyntaxError: dynamic module import is not implemented" when using firefox. I presume it is linked to this issue.

I'm interested in getting firefox support for this, even if the results are not as precise as they should.
Please let me know if/how I can help.

**Comment by rileyjshaw** [comment]
@lukejacksonn adding context to what @Draluy said, there are good reasons for the resolution decrease. See the note at the top of https://developer.mozilla.org/en-US/docs/Web/API/Performance/now:

> The timestamp is not actually high-resolution. To mitigate security threats such as [Spectre](https://spectreattack.com/), browsers currently round the results to varying degrees. (Firefox started rounding to 1 millisecond in Firefox 60.) Some browsers may also slightly randomize the timestamp. The precision may improve again in future releases; browser developers are still investigating these timing attacks and how best to mitigate them.

**Comment by rileyjshaw** [comment]
It's also entirely configurable from Firefox's `about:config` page:

<img width="600" alt="image" src="https://user-images.githubusercontent.com/1840854/55496780-a8918100-55f4-11e9-9369-3513ff35b2b3.png">

**Comment by lukejacksonn** [comment]
Sure, I understand the threat. But why so cautious 2ms? Compared to Chrome and Edge which are both measure with an accuracy in the magnitude of micro seconds.. I guess for me at least, it is a shame to see such a disparity in standards (or sensible defaults).

Good to know the value is configurable at least. Perhaps we could add a note about this this to the README and that would justify merging #8 before I have had chance to test the ops/s measurement approach.

**Comment by Draluy** [comment]
> Compared to Chrome and Edge which are both measure with an accuracy in the magnitude of micro seconds...

Are you sure this is the case and that they are not fuzzing the results while giving the impression of a microsecond accuracy?

**Comment by lukejacksonn** [comment]
I am sure it is sub millisecond otherwise I would't be seeing no results for benchmarks.. but you are right about one thing; they add jitter. Apparently the accuracies are:

- Chrome: 100μs (with 100μs jitter)
- Edge: 20μs (with 20μs jitter)

Which seem perfectly reasonable but 2ms seems certainly unreasonable (worse than new Date()).

**Comment by okwolf** [comment]
This is available behind a flag in the latest Firefox and will be enabled by default in the next version, is it even worth it?

https://caniuse.com/#feat=es6-module-dynamic-import

**Comment by lukejacksonn** [comment]
I didn't know it was going to be available in the next version. Well, that is promising! When is that going to be released do you know? I have been putting off #8 because I really don't want to have to add anything extra 😭

**Comment by okwolf** [comment]
I don't know the Firefox release schedule but it's been in nightly since 18 March. Soon I would hope? 🤷‍♂️

I too would be hesitant to add what looks like a mini transpiler to such a lean mean project. Soon it will only be needed for IE/Edge(until they go Chromium based) support, which I doubt you're targeting for this project.

**Comment by lukejacksonn** [comment]
Fair enough.. yeh, as you can probably tell I am not that symathetic toward these browsers 😅
