### ISSUE TITLE
Test Case for loop

### ISSUE THREAD

**Issue by ninbryan** [lukejacksonn/perflink#6]
Typing out `for loop` stops everything. 
Would like to consider including toggle to auto-run

<img width="989" alt="Screen Shot 2019-04-01 at 3 54 30 PM" src="https://user-images.githubusercontent.com/11507482/55364736-afa27d00-5496-11e9-90cb-f0dffbb5bec8.png">

**Comment by lukejacksonn** [comment]
Ahh yes, good catch 😄 a toggle auto-run and maybe keyboard shortcut to run are on my list of todos! PRs also welcome.

**Comment by lukejacksonn** [comment]
Hey @ninbryan 👋 good news! I just merged #24 and now we don't auto run tests. Hopefully this omits the chance of this happening (although I still haven't accounted for infinite processes so if you hit run with an empty for loop like this then the test might go on forever).

Will keep thinking about these edge cases but until then thanks for the report and your patience 🙇
