### ISSUE TITLE
Color linking / indicators

### ISSUE THREAD

**Issue by atomiks** [lukejacksonn/perflink#7]
Great work @lukejacksonn!

Currently, it's not too difficult to match up the test case with each result, but maybe consider using some color indicators to link them together? The difference between the vertical stacking of the test cases and horizontal stacking of the result bars is slightly confusing to me.

Also, maybe highlight the fastest piece of code?

**Comment by lukejacksonn** [comment]
Thanks for checking it out 🙇 

I love your idea.. but haven't had time to think of an appropriate colour scheme yet. The results were numbered at some point but I removed that. I do agree it needs to be more clear.

Perhaps, preliminarily some reaction to hovering over the test cases could highlight the result in blue or something, and the fastest output could be coloured green?

I will have to think on it a bit more, let me know your thoughts!

**Comment by atomiks** [comment]
> Perhaps, preliminarily some reaction to hovering over the test cases could highlight the result in blue or something, and the fastest output could be coloured green?

I think this is perfect, if you hover over the test case it'll highlight the matching result

**Comment by lukejacksonn** [comment]
Awesome, that will be a quick win. I will try get this implemented asap. Thanks again!

**Comment by lukejacksonn** [comment]
Hey @atomiks 👋 I just merged #24 where the test cases and bars on the graph are now numbered. Not having this was certainly confusing. I didn't got for colours in the end due to all the accessibility foot guns.

Hope this helps and sorry it took so long to implement 🙇
